### ISSUE TITLE
0.1.2 branch seems to be broken

### ISSUE THREAD

**Issue by dodumosu** [neohelden/Flutter-AdaptiveCards#64]
I wanted to build the example app, so I cloned the repository, entered into the `example` folder, and ran `flutter run`. I got an error from `lib/src/flutter_adaptive_cards.dart` on L217: 

> Error: The getter 'ScaffoldMessenger' isn't defined for the class '_AdaptiveCardState'.

I tried changing `pubspec.yml` to reference version 0.1.2 of the package on pub.dev, but it gave the same error. Same thing on checking out the `release-0.1.2` branch. Trying out the `release-0.1.0` branch as I write this.

**EDIT:** was able to build successfully on the `release-0.1.0` branch

**Comment by Curvel** [comment]
Hey @dodumosu, could you provide us the flutter version `flutter --version` and the operating system you try to build for, please? Thanks :)

**Comment by Curvel** [comment]
@dodumosu just tested a bit and indeed v0.1.1 and v0.1.2 don't build on `flutter channel stable`, due to flutter itself has breaking changes. For now, you can use both version by switching to the `flutter channel dev`. We will discuss on how to handle next releases and on how we support the stable channel. So this issue will be fixed with the next flutter stable release.
